# This workflow will run publish a package to NPM when a prerelease tag is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
  # Github Package Registry doesn't handle tags very well so only publishing prereleases to npm
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: Change package version to prerelease tag
        run: |
          sed -i 's/"version": "[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*"/"version": "${{ steps.get_version.outputs.VERSION }}"/' package.json

      - name: 🚀 Publish
        run: yarn npm publish --tag next
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN_PUBLISH__HFC_BOT}}
